language: java

sudo: true

jdk: oraclejdk8

services:
    - postgresql
    - docker

env:
    global:
        - GIT_NAME="Joerg Bellmann"
        - GIT_EMAIL=joerg.bellmann@googlemail.com
        - CI_DEPLOY_USERNAME=jbellmann

script:
    - psql -c 'CREATE DATABASE simple_test;' -U postgres
    - git config user.name "$GIT_NAME"
    - git config user.email "$GIT_EMAIL"
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://$GH_TOKEN:@github.com" > .git/credentials
    - echo $SIGGI_PROJECT_BUILD_NUMBER
    - mvn versions:set -DnewVersion=0.5-$SIGGI_PROJECT_BUILD_NUMBER --batch-mode
    - mvn clean install -Pmaven-docker --batch-mode
    - mvn scm:checkin -DpushChanges=false
    - mvn -Dtag="0.5-$SIGGI_PROJECT_BUILD_NUMBER" scm:tag --batch-mode

